### ISSUE TITLE
About the logistic regression can't converge.

### ISSUE THREAD

**Issue by Shi-Jialiang** [lilianngweta/PISCO#1]
I am interested about this research and when I want to reproduce the result (data all prepared) running the file 'run_cifar10.sh', they told me this mistake:

 '/opt/conda/envs/pisco/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.'. 

I am confused about it cause it seems like the parameters better not to change when you doing the logistic regression and it should be reproduced.

Waiting for your reply.

**Comment by lilianngweta** [comment]
Hi @Shi-Jialiang ... that just means it reached the maximum number of iterations without converging. Even with that warning, you will still get the experiment results. If you want to run it until it converges, try increasing the number of iterations.
